apiVersion: 1

datasources:
  - name: SwiftPipe Loki
    uid: swiftpipe-loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
  - name: SwiftPipe Tempo
    uid: swiftpipe-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: swiftpipe-loki
        tags:
          - key: service.name
            value: service
